# Generated by Django 2.0.3 on 2020-08-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verlag',
            options={'verbose_name_plural': 'Verlage'},
        ),
    ]
