# Generated by Django 3.1 on 2020-08-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karta', '0002_auto_20200829_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karte',
            name='hat_gps',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='karte',
            name='hat_hoehenlinien',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
