# Generated by Django 3.1 on 2020-08-31 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karta', '0003_auto_20200831_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karte',
            name='ablageort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karta.ablageort'),
        ),
        migrations.AlterField(
            model_name='karte',
            name='gebiete',
            field=models.ManyToManyField(blank=True, related_name='karten', to='karta.Gebiet'),
        ),
        migrations.AlterField(
            model_name='karte',
            name='laender',
            field=models.ManyToManyField(blank=True, related_name='karten_in_land', to='karta.Land'),
        ),
        migrations.AlterField(
            model_name='karte',
            name='zwecke',
            field=models.ManyToManyField(blank=True, to='karta.Zweck'),
        ),
    ]
