# Generated by Django 3.1 on 2020-09-01 20:25

import json
from django.db import migrations, models


def convert_to_jsonfield(apps, schema_editor):
    Ansicht=apps.get_model('karta','Ansicht')
    for ansicht in Ansicht.objects.all():
        if ansicht.koords_json is not None:
            ansicht.koords = json.loads(ansicht.koords_json)
            ansicht.save()


class Migration(migrations.Migration):

    dependencies = [
        ('karta', '0004_auto_20200901_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansicht',
            name='koords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(convert_to_jsonfield),
        migrations.RemoveField(
            model_name='ansicht',
            name='koords_json',
        ),
    ]
